Trajectory Following Fixes
iliterobotics/FRC-Robot-2019 pull request #38
Opened 2019-02-03 17:33 UTC by StephenWelch

2019-02-05 22:36 UTC, DanielTolbert requested changes
I think it would be beneficial to document how you arrived to the calculated numbers in the Stronghold Profile class.

2019-02-05 22:53 UTC, DanielTolbert submitted a review, later dismissed

2019-02-07 22:06 UTC, flybotix submitted a review, later dismissed

2019-02-09 15:33 UTC, DanielTolbert approved these changes

2019-02-09 16:51 UTC, flybotix approved these changes

2019-02-09 17:04 UTC, merged